server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_management_system?createDatabaseIfNotExist=true
    username: root
    password: Softgen@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 9000000000000000000
      validation-timeout: 9000000000000000000
      max-lifetime: 9000000000000000000
      connection-timeout: 9000000000000000000

#  jpa:
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true